zhu
ituring/first-pr pull request #1020
Opened 2017-12-01 07:19 UTC by ZhuChengZhong

Please accept my first pull request

2017-12-01 07:20 UTC, ZhuChengZhong commented
#my first comment in github

2017-12-01 07:20 UTC, ZhuChengZhong commented
# haha

2017-12-01 07:21 UTC, ZhuChengZhong commented
# my first comment in github

2017-12-02 08:48 UTC, amaruk requested changes
请在读者留言区以如下格式添加留言：
` <p class="impression">读者留言</p>`
请尝试更新pull request。谢谢。

2017-12-03 19:25 UTC, amaruk commented
请尝试更新并重新提交，谢谢。

2017-12-03 19:25 UTC, closed without merging