Add my impression
ituring/first-pr pull request #1064
Opened 2018-01-06 08:33 UTC by ggglllll

Leave a comment

2018-01-06 08:59 UTC, ggglllll commented
thank you！

2018-01-06 22:21 UTC, amaruk requested changes
请使用UTF-8编码格式。
请尝试更新pull request。
谢谢。

2018-01-07 04:49 UTC, ggglllll commented
我已经改为UTF-8编码格式了，怎么更新pull request？

2018-01-07 09:18 UTC, merged

2018-01-07 09:26 UTC, amaruk commented
只要修改自己的分支并push到自己的仓库，GitHub会自动更新pull request。

一般提交pull request后要检查一下自己提交的pull request里对原仓库的文件到底有哪些源码级的改动。
第一次提交的pull request因为编码格式改变的原因，页面上所有中文字符的编码全都被改变了。
第二次提交的pull request虽然把编码改回了UTF-8，但因为二次转码，部分读者的颜文字留言中，特殊字符由于不同编码字节数不同而被截断，导致乱码。
我在Merge时已修正乱码的部分。