Add my impression
ituring/first-pr pull request #1127
Opened 2018-03-23 08:33 UTC by qipingzhiji

##这是测试pr的

2018-03-23 08:35 UTC, qipingzhiji commented
TEST

2018-03-24 17:21 UTC, amaruk requested changes
请修改后更新pull request。谢谢。

2018-03-24 17:21 UTC, amaruk commented on index.html
> +	  <a href="www.baidu.com">百度</a>
请勿修改读者留言以外的部分，谢谢！

2018-03-26 00:33 UTC, qipingzhiji commented on index.html
> +	  <a href="www.baidu.com">百度</a>
@amaruk 嗯嗯，好的。

2018-03-26 01:03 UTC, qipingzhiji commented
> 请修改后更新pull request。谢谢。

@amaruk  已经修改完毕！

2018-03-26 06:11 UTC, merged