I am sooooo cold
ituring/first-pr pull request #1385
Opened 2018-12-18 14:55 UTC by vangook

天有点冷

2018-12-18 14:56 UTC, vangook commented
管理老师辛苦了：）

2018-12-18 15:13 UTC, vangook commented on index.html
>  <p>本网站是为了让《GitHub入门与实践》读者能尝试在GitHub上进行第一次Pull Request而专门设立的。</p>
commet 1

2018-12-18 15:13 UTC, vangook commented on index.html
>  <p>感谢您购买本书，非常高兴您能亲自尝试书中的例子。</p>
commet 2

2018-12-18 15:14 UTC, vangook reviewed
3 comments of reviewing

2018-12-18 15:14 UTC, vangook commented on index.html
> +<p>最近天有点冷， 没有暖气的南方朋友建议多写写代码，没事用笔记本跑跑集群，发热量应该差不多能捂手（雾）</p>
commet 3

2018-12-18 15:15 UTC, vangook commented on index.html
> +<p>最近天有点冷， 没有暖气的南方朋友建议多写写代码，没事用笔记本跑跑集群，发热量应该差不多能捂手（雾）</p>
reply 1

2018-12-18 15:15 UTC, vangook commented on index.html
> +<p>最近天有点冷， 没有暖气的南方朋友建议多写写代码，没事用笔记本跑跑集群，发热量应该差不多能捂手（雾）</p>
> commet 3

reply 2

2018-12-18 15:15 UTC, vangook commented on index.html
>  <p>本网站是为了让《GitHub入门与实践》读者能尝试在GitHub上进行第一次Pull Request而专门设立的。</p>
> 
> 
> commet 1

reply 1

2018-12-18 15:16 UTC, vangook commented on index.html
>  <p>感谢您购买本书，非常高兴您能亲自尝试书中的例子。</p>
> 
> 
> commet 2

reply 2

2018-12-18 15:32 UTC, vangook commented on index.html
>  <h3>购买链接</h3>
@liubin 老师，请问提交一个PR处在审核期间，在[Files changed]中针对单行代码进行评论，有[Add single comment]和[Start a review]两种选项，请问这两者具体差别在哪呢？因为好像都可以进行多人对话回复

2018-12-18 15:32 UTC, vangook commented on index.html
>  <h3>购买链接</h3>
Pending是为何

2018-12-18 15:34 UTC, vinsec commented on index.html
>  <h3>购买链接</h3>
test

2018-12-18 15:34 UTC, vinsec commented
test

2018-12-18 15:35 UTC, vinsec commented on index.html
>  <p>本网站是为了让《GitHub入门与实践》读者能尝试在GitHub上进行第一次Pull Request而专门设立的。</p>
test

2018-12-18 15:36 UTC, vinsec commented on index.html
>  <p>本网站是为了让《GitHub入门与实践》读者能尝试在GitHub上进行第一次Pull Request而专门设立的。</p>
> test

dasdasd das
sadsad

2018-12-18 15:37 UTC, vinsec reviewed
a

2018-12-18 15:37 UTC, vinsec commented on index.html
> +<p>最近天有点冷， 没有暖气的南方朋友建议多写写代码，没事用笔记本跑跑集群，发热量应该差不多能捂手（雾）</p>
test111

2018-12-19 02:10 UTC, amaruk requested changes
请勿修改读者留言以外的部分。请尝试更新pull request。

2018-12-19 02:13 UTC, amaruk commented on index.html
>    <li><a href="http://www.ituring.com.cn/book/1581">图灵</a></li>
This is a comment.

2018-12-19 02:22 UTC, closed without merging