add
ituring/first-pr pull request #781
Opened 2017-06-06 06:25 UTC by YJCGIT

2017-06-06 06:28 UTC, YJCGIT commented
xiexie

2017-06-06 06:29 UTC, YJCGIT commented
> xiexie

haode

2017-06-08 07:00 UTC, amaruk requested changes
请把读者留言添加到如下代码之后
`<p>(现共有<span id="impression_num"></span>条用户来稿)</p>`

2017-06-11 13:22 UTC, amaruk commented
请把读者留言添加到如下代码之后，尝试重新发起Pull Request。
`<p>(现共有<span id="impression_num"></span>条用户来稿)</p>`

2017-06-11 13:22 UTC, closed without merging