增加我的第一个pull
ituring/first-pr pull request #964
Opened 2017-10-18 16:09 UTC by KeyaJohn

2017-10-18 16:11 UTC, KeyaJohn commented
我只是写了一些文字  希望采纳

2017-10-18 16:11 UTC, KeyaJohn commented
我只是  洗了  一些文字

2017-10-19 06:06 UTC, amaruk requested changes
读者留言请添加到index.html。
请尝试修改并更新pull request。
谢谢。

2017-10-19 14:05 UTC, amaruk requested changes
请尝试revert对README.md的修改，之后编辑index.html文件，在如下HTML代码之后：
`<p>(现共有<span id="impression_num"></span>条用户来稿)</p> `
按照如下格式添加读者留言：
`<p class="impression">读者留言的内容</p> `
谢谢。

2017-10-20 05:48 UTC, amaruk commented
#966 is the final version of pull request.

2017-10-20 05:48 UTC, closed without merging