Create 111
ituring/first-pr pull request #965
Opened 2017-10-18 16:15 UTC by KeyaJohn

第一次   pu'll

2017-10-18 16:15 UTC, KeyaJohn commented
哈哈哈哈或

2017-10-19 06:07 UTC, amaruk requested changes
同Pull Request #964

2017-10-19 14:20 UTC, KeyaJohn commented
为什么我修改了请求合并怎么没有pull request 选项了

2017-10-20 05:48 UTC, amaruk commented
#966 is the final version of pull request.

2017-10-20 05:48 UTC, closed without merging